stages:
  - client
  - server
  - docker

client:
  stage: client
  image: node:lts
  script:
    - make client

server:
  stage: server
  image: golang:latest
  script:
    - make server

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker restart Pernthaler