name: Build

on:
  push:
    branches:
      - "master"

jobs:

  github:
    name: GitHub
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Build
        run: |
          make
          echo VERSION=$(./server/Website.exe -v | cut -d ' ' -f 3) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: server/Website.exe
          tag_name: v${{ env.VERSION }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    docker:
      name: Docker
      runs-on: linux-latest
      steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          
      - name: Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          check-latest: true

      - name: Build
        run: |
          make
          echo VERSION=$(./server/website -v | cut -d ' ' -f 3) >> $GITHUB_ENV

      - name: Login
        uses: docker/login-action@v2
        with:
          username: pernthaler
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          tags: |
            pernthaler/website:${{ env.VERSION }}
            pernthaler/website:latest