name: Build

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:

            - name: Checkout
              uses: actions/checkout@v4

            - name: Java
              uses: actions/setup-java@v3
              with:
                  distribution: zulu
                  java-version: 21

            - name: Build
              run: |
                  chmod +x gradlew
                  echo VERSION=$(./gradlew -q properties | grep 'version:' | cut -d ' ' -f 2) >> $GITHUB_ENV
                  ./gradlew build

            - name: Release
              uses: softprops/action-gh-release@v1
              with:
                  files: build/libs/*.jar
                  tag_name: ${{ env.VERSION }}
                  fail_on_unmatched_files: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Login
              uses: docker/login-action@v3
              with:
                  username: pernthaler
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push
              uses: docker/build-push-action@v5
              with:
                  context: .
                  push: true
                  tags: |
                      pernthaler/website:${{ env.VERSION }}
                      pernthaler/website:latest