name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout GitHub
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Build Yarn
        run: |
          yarn install
          yarn build

      - name: Get Version
        run: |
          sudo apt-get install jq
          echo VERSION=$(jq -r .version package.json) >> $GITHUB_ENV

      - name: Login Docker
        uses: docker/login-action@v1
        with:
          username: pernthaler
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Sync Docker
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: pernthaler
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: pernthaler/website
          readme: README.md

      - name: Push Docker
        uses: docker/build-push-action@v2
        with:
          push: true
          context: .
          tags: |
            pernthaler/website:latest
            pernthaler/website:${{ env.VERSION }}

      - name: Release GitHub
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}