name: Build

on:
  push:
    branches:
      - master

jobs:

  todo:
    run: echo TODO

#  TODO
#  github:
#    uses: ./.github/workflows/github.yml@github

#  TODO
#  docker:
#    uses: ./.github/workflows/docker.yml@docker