name: Build

on:
  push:
    branches:
      - master

jobs:

#  TODO
#  github:
#    uses: ./.github/workflows/github.yml
#    secrets: inherit

  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit