name: Build

on:
  push:
    branches:
      - master

jobs:

  github:
    uses: ./.github/workflows/github.yml
    secrets: inherit

  docker:
    uses: ./.github/workflows/docker.yml
    secrets: inherit