name: Build

on:
  push:
    branches:
      - master

jobs:

  todo:
    runs-on: ubuntu-latest
    steps:
      - run: echo TODO

#  TODO
#  github:
#    uses: ./.github/workflows/github.yml

  docker:
    uses: ./.github/workflows/docker.yml