on: workflow_call
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

#      - name: Go
#        uses: actions/setup-go@v3
#        with:
#          go-version: 1.19
#          check-latest: true

      - name: Build
        run: |
          make
          echo VERSION=$(./bin/website -v | cut -d ' ' -f 3) >> $GITHUB_ENV

      - name: Login
        uses: docker/login-action@v2
        with:
          username: pernthaler
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push
        uses: docker/build-push-action@v3
        with:
          push: true
          context: .
          file: build/docker/Dockerfile
          tags: |
            pernthaler/website:${{ env.VERSION }}
            pernthaler/website:latest