on: workflow_call
jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
          echo VERSION=$(./target/release/website -V | cut -d ' ' -f 2) >> $GITHUB_ENV

      - name: Login
        uses: docker/login-action@v2
        with:
          username: pernthaler
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            pernthaler/website:${{ env.VERSION }}
            pernthaler/website:latest