on: workflow_call
jobs:
  github:
    name: GitHub
    runs-on: windows-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: |
          npm install -g pnpm
          pnpm install
          pnpm build
          echo VERSION=$(./target/release/website.exe -V | cut -d ' ' -f 3) | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: target/release/website.exe
          tag_name: v${{ env.VERSION }}
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}