name: Version

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Version
        run: |
          sudo apt-get install jq
          echo VERSION=$(jq -r .version package.json) >> $GITHUB_ENV
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}