name: Storybook
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: '>=15.0.0'
          check-latest: true
      
      - name: Install dependencies
        run: npm install
      
      - name: Run github script
        run: npm run github
