name: Storybook
on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: '>=15.0.0'
          check-latest: true
      
      - name: Build
        run: |
          npm install
          npm run github
  
      - name: Deploy
        run: |
          git add storybook-static
          git commit -m "Update Storybook"
          git subtree push --prefix storybook-static origin storybook
